<!-- page3.php page of Project 1 requires the user to complete 2 fields, indicating how they made their purchases and which purchases they made. Upon completion of these fields, the user will click the next button to access thank you display-->
<?php
//session_start() is called at the beginning of each page to create a session or resume the current one. If the session page is not set it will be set to 0 (the index(start) page). Then through a series of if else if statements, it is determined what the $_SESSION @ page is == to then through the use of JavaScript location.assign, the user is sent to the page they should be on based on their session data.
	session_start();
	
	if(!isset($_SESSION['page'])){
		$_SESSION['page']= 0;
	}
	if ($_SESSION['page']== 0){
	?>
	<script>location.assign('./index.php');</script>
	<?php
	}
	else if ($_SESSION['page']== 1){
	?>
	<script>location.assign('./page1.php');</script>
	<?php
	}
	else if ($_SESSION['page']== 2){
	?>
	<script>location.assign('./page2.php');</script>
	<?php
	}

?>

<html>
<head>
	<title>Diana's Project 1 - Survey - Page 3</title>
	<!--link to external cascading style sheet (CSS)-->
	<link href="./main.css" type="text/css" rel="stylesheet"/>
	<!--link to applicable Google fonts-->
	<link href="https://fonts.googleapis.com/css?family=Rubik|Trirong" rel="stylesheet">
	
</head>
<body>
	<div id="wrap">
	<header>
	<h1>Survey - Page 3</h1>
	</header>
	

	<form method="POST" action="./page3.php">
		<!--this statement will be complete if the server request method is == to post (which is true as the method for the form is "POST"). This evaluation to true will occur when the user clicks the "submit" button. Validate_fields is invoked and if any errors occur then display_error is invoked, if not then display_success in invoked, else form 1 is invoked with the variables from the . ... foreach loops within statement allow for multiple products to present, if and when multiple products were purchased-->
	<?php if ($_SERVER['REQUEST_METHOD'] == 'POST'){
		
				$error_msg = validate_fields();
		if (count($error_msg) > 0){
			display_error($error_msg);
			foreach($_SESSION['purchaseData'] as $purchaseInfo){
				surveyForm($purchaseInfo);
			}
		} else {
			display_success();
		}
	} else {
		foreach($_SESSION['purchaseData'] as $purchaseInfo){
				surveyForm($purchaseInfo);
			}
	} ?>
	<input type="submit" value="Submit"/>
	</form>
	
</div>
</body>
</html>
	
	<!--php function form_1 is here, beneath it is the form created for user input and in turn validation. At the bottom of the form (the last element) is a "submit" button, which upon clicking causing the above to run.-->
	<?php function surveyForm($purchaseInfo){?>
	


		<h1>Please complete the following questions for the <?php echo"$purchaseInfo"?> you purchased with us</h1>

		<label>How happy are you with this device on a scale from 1 (not satisfied) to 5 (very satisfied)?</label>	
		<br>	
		<!--the name for the radio buttons and select options below are generated by inserting a php line of code within the name quoations, where the purchaseInfo will be echoed and concatenated with satisfaction[] to create an array (or recommend in the case of the select options).-->
		<input type="radio" name="<?php echo"$purchaseInfo"?>satisfaction[]" value="1"> 1<br>
		<input type="radio" name="<?php echo"$purchaseInfo"?>satisfaction[]" value="2"> 2<br>
		<input type="radio" name="<?php echo"$purchaseInfo"?>satisfaction[]" value="3"> 3<br>
		<input type="radio" name="<?php echo"$purchaseInfo"?>satisfaction[]" value="4"> 4<br>
		<input type="radio" name="<?php echo"$purchaseInfo"?>satisfaction[]" value="5"> 5<br>

		<br>

		<label>Would you recommend the purchase of this device to a friend?</label>
		<select name="<?php echo"$purchaseInfo"?>recommend">
		<option selected="true" disabled="disabled"> </option>  
		<option value="Yes">Yes</option>
		<option value="no">No</option>
		</select>
		<br>

	<?php  }?>


<!--validate_field function: verifies all fields fields are set, thereby ensuring they have been selected by the user. -->
	<?php function validate_fields(){
		$error_msg = array();
		foreach($_SESSION['purchaseData'] as $purchaseInfo){
			if (!isset($_POST[$purchaseInfo.'satisfaction'])){
				$error_msg[] = "Satisfaction value is not selected for ".$purchaseInfo;
			}
		}

		foreach($_SESSION['purchaseData'] as $purchaseInfo){	
			if (!isset($_POST[$purchaseInfo.'recommend'])){
				$error_msg[] = "Recommend value is not selected for ".$purchaseInfo;
			}}
		return $error_msg;

 }?>

<!--the display_error function passes through argument of $error_msg, as defined (returned) by function validate_fields. If there are error messages generated for either of the fields, there is a foreach loop within this function which will allow one, or both errors to be displayed, depending on how many errors occurred-->

 <?php function display_error($error_msg){
	echo "<p>\n";
	foreach($error_msg as $v){
		echo $v."<br>\n";
	}
	echo "<p>\n";
} ?>

 <!--if the display_success method below is invoked the validate_fields has run successfully without errors. On this final page of the survey the  ession page will not be set, but rather a table will be dynamically generated and displayed to the user. A simple html table structure is used to clearly output the data the user input. This is completed by using php inside the fields to echo the previously saved session data. The dynamically generated fields and data are done so, again, using php code inserted into the html, which sets a foreach loop for the purchaseData-->
 <?php function display_success(){ 
 	
?>

<h1>THANK YOU FOR TAKING OUR SURVEY</h1>

<table>
	<tr> 
		<td>Name: <?php echo $_SESSION['userFullName']; ?></td>
	</tr>
	<tr> 
		<td>Age: <?php echo $_SESSION['userAge']; ?></td>
	</tr>
	<tr> 
		<td>Student Status: <?php echo $_SESSION['isStudent']; ?></td>
	</tr>
	<tr> 
		<td>How you made your purchase: <?php echo $_SESSION['purchaseMethod']; ?></td>
	</tr>
<?php foreach($_SESSION['purchaseData'] as $purchaseInfo){
			
	?>
	<tr> 
		<td>What you purchased: </td>
		<td><?php echo $purchaseInfo; ?></td>
	</tr>
	<tr> 
		<td>Satisfaction Rating: </td>
		<td><?php echo $_POST[$purchaseInfo.'satisfaction'][0]; ?></td>
	</tr>
	<tr>
		<td>Recommend: </td>
		<td><?php echo $_POST[$purchaseInfo.'recommend']; ?></td>
	</tr>
	
<?php }?>
</table>

<?php
} ?>

